# Generated by Django 5.0.6 on 2026-05-07 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_service_bookingitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='negotiation_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='negotiation_status',
            field=models.CharField(choices=[('none', 'None'), ('customer_proposed', 'Customer Proposed'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='proposed_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
