# Generated by Django 5.0.6 on 2026-05-06 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(default='wrench', max_length=50),
        ),
    ]
