# Generated by Django 5.0.6 on 2026-05-07 04:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_category_icon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderKYCDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('govt_id_type', models.CharField(blank=True, choices=[('aadhaar', 'Aadhaar Card'), ('pan', 'PAN Card'), ('driving_license', 'Driving License'), ('passport', 'Passport')], max_length=20)),
                ('govt_id_number', models.CharField(blank=True, max_length=50)),
                ('id_front', models.ImageField(blank=True, null=True, upload_to='kyc/id/')),
                ('id_back', models.ImageField(blank=True, null=True, upload_to='kyc/id/')),
                ('selfie', models.ImageField(blank=True, null=True, upload_to='kyc/selfie/')),
                ('kyc_status', models.CharField(choices=[('not_submitted', 'Not Submitted'), ('pending_review', 'Pending Review'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='not_submitted', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('provider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc', to='services.providerprofile')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc_reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
