# Generated by Django 5.0.6 on 2026-05-07 05:05
# Hand-edited: through-model table was partially created by a failed attempt,
# so SeparateDatabaseAndState is used to sync Django state with the real DB.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_providerkycdocument'),
    ]

    operations = [
        # Table already exists in DB from the failed first attempt — only update state.
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name='ProviderService',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('custom_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                        ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_services', to='services.providerprofile')),
                        ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service')),
                    ],
                    options={
                        'unique_together': {('provider', 'service')},
                    },
                ),
            ],
        ),
        # Drop the old implicit join table services_providerprofile_services.
        migrations.RemoveField(
            model_name='providerprofile',
            name='services',
        ),
        # Re-add as through-model M2M — DB table already exists, only update state.
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='providerprofile',
                    name='services',
                    field=models.ManyToManyField(blank=True, related_name='providers', through='services.ProviderService', to='services.service'),
                ),
            ],
        ),
    ]
